### PR TITLE
New --devicons option to show icons based on file type (requires patched mono font)

### PR DESCRIPTION
**Pull request by scottbilas**
Ok this one is a bit sillier. I did it to match my ranger file browser setup. :) What do you think?

image

### CODE REVIEW

**Comment by jpwilliams** [comment]
Aha well that is definitely silly, but it does look very cool. 😁

Is it usual to have packages sometimes rely on system-based things like fonts? It'd be wonderful to have this as the default, but it doesn't appear as if there's a pretty way to do that.

Fantastically pretty, though. Going to have a poke around and see if there's an even nicer way. :)

**Comment by jpwilliams** [comment]
I'm okay with it, as it's optional and there are quite a few packages around that look like they rely on Nerd Fonts. That said, I don't like the way every package defines their own suffixes like in [utils/devicon.js](https://github.com/scottbilas/gitree/blob/pr/devicons/utils/devicon.js#L9-L125). A module that provides this map (that other modules could use, too) would seem like the better way!

Do you know of any lists like that that already exist, @scottbilas? Or maybe we should just make one...

**Comment by scottbilas** [comment]
I agree, it would be great if there were a common package that could be reused. Ideally something that could be shared across languages as well..maybe via install script+codegen. It might be that something already exists, would be cool to add one if not, but I have never done node.js-based dev before and this whole world is all new to me..

**Comment by jpwilliams** [comment]
I've been very quiet on this, @scottbilas, and I apologise for that! Started a new job recently so haven't had a lot of time to look at these projects. 😃

When I get time I'll make a few styling changes to this, but then I think it's all good to merge it in! I want those icons! 😉

**Comment by scottbilas** [comment]
Nice!

**Pull request merged**
